---
- hosts: mysql_server
  become: yes
# Wczytanie zmiennych 
  vars_files:
  - /vaults/vault-ansible.yml

  - name: Uruchomienie usługi MySQL
    service:
      name: mysql
      state: started
      enabled: yes
    
  - name: Stworzenie nowej bazy danych
    mysql_db:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ new_mysql_database }}"
      state: present

  - name: Stworzenie nowego użytkownika i nadanie uprawnień  
    mysql_user:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      name: "{{ new_mysql_user }}"
      password: "{{ new_mysql_password }}"
      priv: "{{ new_mysql_database }}.*:ALL"
      state: present

  - name: Ustawienie rozmiaru bufora
    lineinfile:
      path: /etc/mysql/my.cnf
      regexp: '^innodb_buffer_pool_size'
      line: 'innodb_buffer_pool_size = {{ buffer_pool_size }}'
  
  - name: Konfiguracja logów binarnych
    lineinfile:
      path: /etc/mysql/my.cnf
      regexp: '^log_bin'
      line: 'log_bin = /var/log/mysql/mysql-bin.log'

  - name: Restart usługi MySQL 
    service:
      name: mysql
      state: restarted  

  - name: Konfiguracja replikacji bazy danych
    block:
    - name: Konfiguracja serwera głównego
      when: "'{{ inventory_hostname }}' == '{{ master_server_ip }}'"
      block:
      - name: Konfiguracja ID serwera
        lineinfile:
          path: /etc/mysql/my.cnf
          regexp: '^server-id'
          line: 'server-id = 1'
      - name: Utworzenie użytkownika replikacji
        mysql_user:
          login_user: root
          login_password: "{{ mysql_root_password }}"
          name: "{{ replication_user }}"
          password: "{{ replication_password }}"
          priv: "*.*:REPLICATION SLAVE"
          state: present

    - name: Konfiguracja serwera podrzędnego bazy danych
      when: "'{{ inventory_hostname }}' == '{{ slave_server_ip }}'"
      block:
      - name: Konfiguracja ID serwera
        lineinfile:
          path: /etc/mysql/my.cnf
          regexp: '^server-id'
          line: 'server-id = {{ server_id }}'
      - name: Konfiguracja szczegółów replikacji
        command: mysql -u root -p'{{ mysql_root_password }}' -e "CHANGE MASTER TO MASTER_HOST='{{ master_server_ip }}', MASTER_USER='{{ replication_user }}', MASTER_PASSWORD='{{ replication_password }}', MASTER_LOG_FILE='mysql-bin.000001';"
      - name: Uruchomienie serwera podrzędnego
        command: mysql -u root -p'{{ mysql_root_password }}' -e "START SLAVE;"

  - name: Backup bazy danych
    block:
    - name: Dump bazy danych
      command: mysqldump -u root -p'{{ mysql_root_password }}' {{ new_mysql_database }} > {{ backup_dir }}/backup.sql
    - name: Ustawienie uprawnień do pliku
      file:
        path: "{{ backup_dir }}/backup.sql"
        mode: '0600'

  - name: Instalacja OpenSSL do szyfrowania
    apt:
      name: openssl
      state: present

  - name: Szyfrowanie kopii zapasowej
    command: openssl enc -aes-256-cbc -salt -in {{ backup_dir }}/backup.sql -out {{ backup_dir }}/backup.sql.enc -pass pass:'{{encryption_password}}'

